* ## Numpy, stands for numeric python, is a library consisting of multidimensional array objects.
* ## Using numpy mathematical and logical operations on array can be performed.
* ## If you are on linux distro then use "pip3 install numpy" to install numpy in your system

In [2]:
import numpy as np   #Numpy is an object so we have to import it in our project
a = "hello world"
print(a, type(a))    #type(a) will tell you what type of object it is.

hello world <class 'str'>


## Basic syntax of numpy.array:-
### numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

* ### Example1: 

In [3]:
b = np.array([1,2,3])    #creating a 1-d array

# The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.
# Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).

print(b, type(b))        

[1 2 3] <class 'numpy.ndarray'>


* ### Example2:

In [7]:
b = np.array([[1,2],[3,4]])   #2-d array
print(b,'\n\n type is', b[0], end='\n\n')
c = np.asmatrix(b)            #this is same as previous asmatrix also do the same thing
print(c, c[1,1], b[1,1])

[[1 2]
 [3 4]] 

 type is [1 2]

[[1 2]
 [3 4]] 4 4


* ### Example3:

In [10]:
b = np.array([1,2,3,4,5], ndmin=2)   #ndmin=2 attribute tells the numpy that we want to use 2-d array so it will convert the array for us
print(b,'\n\n', b.ndim,'\n\n', b.shape)    #shape attribute tells that how many rows, cols array has

[[1 2 3 4 5]] 

 2 

 (1, 5)


* ### Example4:

In [24]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


### ->To see the documentation of any method/property use that method follows with '?'

In [17]:
np.mat?   #np.mat interpret the input as matrix

## Numpy datatypes:-

### numpy.dtype(object, align, copy)

In [21]:
dt = np.dtype(np.int64)
print(dt)

# int8 -> i1
# int16 -> i2
# int 32 -> i4
# int64 -> i8

dt2 = np.dtype('>i2')
print(dt2)

int64
>i2


In [27]:
#structured data type
#here S20 is 20 bit long string
dt = np.dtype([('age','i1'),('name', 'S20')])   #This indicates that this type of datatype contain tuples in which first element represent age(type i1 = int8) and second one represent name(type=s20 (means 20 character long string))
print(dt)

[('age', 'i1'), ('name', 'S20')]


In [28]:
a = np.array([(10,"ggg"),(20,'sourabh')], dtype=dt)   #Here we are declaring the arrray with the previous made datatype dt
print(a, end='\n\n')
print(a['name'])

[(10, b'ggg') (20, b'sourabh')]

[b'ggg' b'sourabh']


# ndarray.shape

### In simple statement we can say that shape tell you the structure of the array like how many rows, and columns that array has

### Example1,2

In [12]:
a = np.array([[1,2,3],[4,5,6]])
print(a, a.shape, end='\n\n')
a.shape = (3,2)   #changing the shape to 3 rows, 2 col from 2rows, 3 cols
print(a)

[[1 2 3]
 [4 5 6]] (2, 3)

[[1 2]
 [3 4]
 [5 6]]


### Example3

In [88]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)    #we can use reshape also to do the previous work
print(b)

[[1 2]
 [3 4]
 [5 6]]


# ndarray.ndim

### This array attribute returns the number of array dimensions.

### Example1

In [34]:
# arange is use to give you elements starting from 0 till the mentioned element
# to see the documentation of it always feel free to use 

np.arange?
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### Example2

In [13]:
a = np.arange(24)
print(a.ndim)        #which is 1

# reshaping 

b = a.reshape(2,4,3)   #trying to convert 24 elements in 3-d
print(b)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


# numpy.itemsize

### This array attribute returns the length of each element of array in bytes.

In [99]:
x = np.array([1,2,3,4,5], dtype='i4')
print(x.itemsize)    #it returns the size of element of array in byte

4


## numpy.flags

In [105]:
x = np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


# numpy.empty

### it initialize the array with random values

In [18]:
x = np.empty([3,2], dtype='i8')
print(x, x.dtype)

[[1 2]
 [3 4]
 [5 6]] int64


# numpy.zeros
### Returns a new array of specified size, filled with zeros.

In [19]:
x = np.zeros(5)
print(x, x.itemsize)

[0. 0. 0. 0. 0.] 8


In [20]:
x = np.zeros(5, dtype=np.int)
print(x, x.itemsize)

[0 0 0 0 0] 8


In [26]:
dt = np.dtype([('x','i4'), ('y','i1')])
x = np.zeros((2,2), dtype=dt)
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


# numpy.ones
### Returns a new array of specified size and type, filled with ones.

In [27]:
x = np.ones(4)
print(x, end='\n\n')

x = np.ones([2,2], dtype=np.int)
print(x)

[1. 1. 1. 1.]

[[1 1]
 [1 1]]


# numpy.asarray
### This function is similar to numpy.array except for the fact that it has fewer parameters.
### numpy.asarray(a, dtype = None, order = None)

In [35]:
# np.asarray?
# uncomment above statement to see the documentation of asarray

a = [[1,2,3],[4,5,6]]
b = np.asarray(a, dtype=float)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


### ndarray from tuple and list of tuples

In [31]:
x = (1,2,3)
a = np.asarray(x)
print(a,end='\n\n')


#now from list of tuples
x = [(1,2,3),(4,5)]
a = np.asarray(x)
print(a,end='\n\n')


x = [(1,2,3),(4,5,6)]    #difference is if the both tuples has same no of elements then it converts all of them in a array where rows= no of tuples and col=no of elements in those tuples
a = np.asarray(x)
print(a)

[1 2 3]

[(1, 2, 3) (4, 5)]

[[1 2 3]
 [4 5 6]]


# numpy.fromiter

### Used to iterate over any iterable object, which can be any string, array and so on

In [37]:
import numpy as np 
list = range(5)
print([x for x in list])

[0, 1, 2, 3, 4]


In [38]:
it = iter(list)
print(it)   #as you can see iter creates object of that list and now we can iterate it
x = np.fromiter(it, dtype=float)   #changing the datatype of the list from int to float
print(x)

[0. 1. 2. 3. 4.]


# numpy.arange

### numpy.arange(start, stop, step, dtype)

In [154]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [155]:
x = np.arange(5, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [156]:
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


# numpy.linespace

### This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified.

### numpy.linspace(start, stop, num, endpoint, retstep, dtype)


In [161]:
x = np.linspace(10,200)    #which shows the default num=50
print(x)

[ 10.          13.87755102  17.75510204  21.63265306  25.51020408
  29.3877551   33.26530612  37.14285714  41.02040816  44.89795918
  48.7755102   52.65306122  56.53061224  60.40816327  64.28571429
  68.16326531  72.04081633  75.91836735  79.79591837  83.67346939
  87.55102041  91.42857143  95.30612245  99.18367347 103.06122449
 106.93877551 110.81632653 114.69387755 118.57142857 122.44897959
 126.32653061 130.20408163 134.08163265 137.95918367 141.83673469
 145.71428571 149.59183673 153.46938776 157.34693878 161.2244898
 165.10204082 168.97959184 172.85714286 176.73469388 180.6122449
 184.48979592 188.36734694 192.24489796 196.12244898 200.        ]


In [40]:
x = np.linspace(1,2,5, endpoint=False, retstep=True)
print(x)
x = np.linspace(1,2,5, endpoint=False, retstep=False)
print(x)

(array([1. , 1.2, 1.4, 1.6, 1.8]), 0.2)
[1.  1.2 1.4 1.6 1.8]


# numpy.logspace

### This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.

### numpy.logspace(start, stop, num, endpoint, base, dtype)

In [164]:
x = np.logspace(1,2, num=10)
print(x)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [165]:
x = np.logspace(start=1, stop=10, num=10, endpoint=True, base=2)
print(x)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


# numpy indexing and slicing

### we use slice function with parameters of start, stop, step

In [169]:
a = np.arange(10)
s = slice(2,7,2)
print(a[s])

[2 4 6]


### Another way of writing

In [180]:
a = np.linspace(0,10, num=10, dtype=int)
b = a[2:7:2]
print(b)

print()
print(a[:])
print(a[2:])
print(a[2:5])
print(a[5])

[2 4 6]

[ 0  1  2  3  4  5  6  7  8 10]
[ 2  3  4  5  6  7  8 10]
[2 3 4]
5


In [45]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

print("Now we will slice the array from the index a[1:]")
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [48]:
print(a[...,1])      #elements of first column
print(a[0,...])      #elements of 0th row
print(a[...,1:])     #elements after first column
print(a[1,2])

[2 4 5]
[1 2 3]
[[2 3]
 [4 5]
 [5 6]]
5


# Advance Indexing

### Example1

In [63]:
x = np.array([[1, 2],[3,4],[5,6]])
y = x[1,1]
z = x[[0,1,2],[0,1,0]]
print(x,y,z)

[[1 2]
 [3 4]
 [5 6]] 4 [1 4 5]


### Example2

In [75]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x,end='\n\n')
print(x[[[0,0],[3,3]],[[0,2],[0,2]]])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  2]
 [ 9 11]]


### Example3

In [74]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x,end='\n\n')

# Advance slicing method1
z = x[1:4, 1:3]
print(z,end='\n\n')

# Advance slicing method2
y = x[ [ [1,1], [2,2], [3,3] ], [ [1,2], [1,2], [1,2] ] ]
print(y, end='\n\n')

# Advance slicing method3
c = x[1:4,[1,2]]
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 4  5]
 [ 7  8]
 [10 11]]

[[ 4  5]
 [ 7  8]
 [10 11]]

[[ 4  5]
 [ 7  8]
 [10 11]]


### Example4

In [76]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x, end='\n\n')

y = [x>5]
print(y, end='\n\n')

z = x[y]
print(z)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])]

[ 6  7  8  9 10 11]


### Example5

In [84]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
b = a[~np.isnan(a)]

print(b)

[1. 2. 3. 4. 5.]


### Example6

In [85]:
s = np.array([1, 2+6j, 5, 3.5+5j])
print(s[np.iscomplex(s)])

[2. +6.j 3.5+5.j]


# Broadcasting

- ### Example1

In [87]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a*b)
# Here the dimension are same

[ 6 14 24 36 50]


* ### Example2

In [89]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a*b)
# Here the dimension are same

[ 6 14 24 36 50]


# Iterating Over Array

* ### Example1

In [94]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a, end='\n\n')
for x in np.nditer(a):
    print(x, end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

0 5 10 15 20 25 30 35 40 45 50 55 

* ### Example2

In [95]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a, end='\n\n')
b = a.T
print(b, end='\n\n')
for x in np.nditer(b):
    print(x,end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]

0 5 10 15 20 25 30 35 40 45 50 55 

* ### Example3 Iteration order

In [96]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a,end='\n\n')
b = a.T
print(b, end='\n\n')
c = b.copy(order='C')
print(c, end='\n\n')

for x in np.nditer(c):
    print(x, end=' ')

print()
d = b.copy(order='F')
print(d, end='\n\n')
for x in np.nditer(d):
    print(x, end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]

0 20 40 5 25 45 10 30 50 15 35 55 
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]

0 5 10 15 20 25 30 35 40 45 50 55 

* ### Example4

In [97]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a, end='\n\n')
for x in np.nditer(a, order='C'):
    print(x, end=' ')
print()

for x in np.nditer(a, order='F'):
    print(x, end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

0 5 10 15 20 25 30 35 40 45 50 55 
0 20 40 5 25 45 10 30 50 15 35 55 

* ### Example5   Modifying Array Values

In [102]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a, end='\n\n')
# for x in np.nditer(a, op_flags = ['readwrite']):
#     x[...] = 2*x
a = a*2
for x in np.nditer(a, op_flags=['read'])
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [108]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a, end='\n\n')
for x in np.nditer(a, flags=['external_loop'], order='F'):
    print(x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


* ### Example6 Broadcasting Iteration

In [109]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a, end='\n\n')
b = np.array([1,2,3,4], dtype=int)
print(b, end='\n\n')
for x,y in np.nditer([a,b]):
    print("%d:%d" %(x,y))

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

[1 2 3 4]

0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


# Array Manipulation

* ### reshape

In [112]:
a = np.array([[1,2,3], [4,5,6]])
print(a,np.reshape(a, 6))

print(np.reshape(a, 6, order='F'))

[[1 2 3]
 [4 5 6]] [1 2 3 4 5 6]
[1 4 2 5 3 6]


* ### flat

In [116]:
a = np.arange(8).reshape(2,4)
print(a,end='\n\n')
print(a.flat[5])

# flat function iterate the array in 1d fashion

[[0 1 2 3]
 [4 5 6 7]]

5


* ### flatten->used to give 1d version of array

In [124]:
a = np.arange(8).reshape(2,4)
print(a,end='\n\n')
print(a.flatten())
print(a.flatten(order='F'))

[[0 1 2 3]
 [4 5 6 7]]

[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


* ### revel-> it also give 1d version of array

In [125]:
a = np.arange(8).reshape(2,4)
print(a, end='\n\n')
print(a.ravel())
print(a.ravel(order='F'))

[[0 1 2 3]
 [4 5 6 7]]

[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


* ### Numpy Transpose

In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a)
print(a,end='\n\n')
print(b)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
